### ISSUE TITLE
Can't build flask app with requirements of guesslang 0.9.3

### ISSUE THREAD

**Issue by jmaks** [psty-io/psty-api#18]
When trying to resolve dependencies of modules via pip
```
# pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: absl-py==0.7.1 in ./.flaskapp/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (0.7.1)
Requirement already satisfied: aniso8601==7.0.0 in ./.flaskapp/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (7.0.0)
Requirement already satisfied: astor==0.8.0 in ./.flaskapp/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (0.8.0)
Requirement already satisfied: Click==7.0 in ./.flaskapp/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (7.0)
Requirement already satisfied: Flask==1.0.3 in ./.flaskapp/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (1.0.3)
Requirement already satisfied: Flask-RESTful==0.3.7 in ./.flaskapp/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (0.3.7)
Requirement already satisfied: gast==0.2.2 in ./.flaskapp/lib/python2.7/site-packages (from -r requirements.txt (line 7)) (0.2.2)
Requirement already satisfied: grpcio==1.21.1 in ./.flaskapp/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (1.21.1)
Requirement already satisfied: h5py==2.9.0 in ./.flaskapp/lib/python2.7/site-packages (from -r requirements.txt (line 9)) (2.9.0)
ERROR: Could not find a version that satisfies the requirement guesslang==0.9.3 (from -r requirements.txt (line 10)) (from versions: 0.9.0rc5, 0.9.1, 2.0.0a1, 2.0.0, 2.0.1, 2.0.3, 2.2.0, 2.2.1)
ERROR: No matching distribution found for guesslang==0.9.3 (from -r requirements.txt (line 10))


```
Tried to change version of guesslang to 0.9.1, 2.0.0 or so, got some another errors 
```
# pip install guesslan
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting guesslang
  Using cached guesslang-2.2.1.tar.gz (2.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/username/psty-api/.flaskapp/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tU4xYL/guesslang/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tU4xYL/guesslang/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1qgHB3
         cwd: /tmp/pip-install-tU4xYL/guesslang/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tU4xYL/guesslang/setup.py", line 24
        def version(base_module: str) -> str:
                               ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jmaks** [comment]
```
# python --version
Python 2.7.12

# pip -V 
pip 20.3.4 from /home/username/psty-api/.flaskapp/local/lib/python2.7/site-packages/pip (python 2.7)
```

Also tried to change to python3 (version Python 3.5.2) and can't to resolve errors
